### ISSUE TITLE
无法找到数据文件

### ISSUE THREAD

**Issue by Adrn1n** [Ice-W0lf/PMMAA#5]
无法找到部分ipynb中需要读入的数据文件(如每章的hw), 在release的data-and-code中也无法找到
请求补上, 非常感谢!

**Comment by hacheyz** [comment]
你好，请你提供几个缺失的具体数据文件示例，以便我对照处理，谢谢！

**Comment by Adrn1n** [comment]
> 你好，请你提供几个缺失的具体数据文件示例，以便我对照处理，谢谢！

比如"04 线性规划和整数规划模型"中的"4 hw.ipynb"里的所有"ti4_x"文件.

不过没关系, 我已经在其他平台上找到了

**Comment by hacheyz** [comment]
你好，hw 依赖的相关文件已在[最新的 Release](https://github.com/hacheyz/PMMAA/releases/tag/v1.1.0) 中补充，感谢你的贡献！
